package com.syncro.domain.model

data class Quote(
    val text: String,
    val author: String
)

object QuotesProvider {
    val quotes = listOf(
        Quote("La mejor manera de empezar es dejar de hablar y empezar a hacer.", "Walt Disney"),
        Quote("El pesimista ve dificultad en toda oportunidad. El optimista ve oportunidad en toda dificultad.", "Winston Churchill"),
        Quote("No dejes que el ayer ocupe demasiado del hoy.", "Will Rogers"),
        Quote("Aprendes más del fracaso que del éxito. No dejes que te detenga. El fracaso construye el carácter.", "Anónimo"),
        Quote("No se trata de si te derriban, se trata de si te levantas.", "Vince Lombardi"),
        Quote("Si estás trabajando en algo que realmente te importa, no tienes que ser empujado. La visión te atrae.", "Steve Jobs"),
        Quote("La gente que está lo suficientemente loca como para pensar que pueden cambiar el mundo, son los que lo hacen.", "Rob Siltanen"),
        Quote("El fracaso nunca me alcanzará si mi determinación por triunfar es lo suficientemente fuerte.", "Og Mandino"),
        Quote("Los emprendedores son expertos en enfrentar la incertidumbre y también expertos en minimizar el riesgo. Eso es el optimismo clásico.", "Mohnish Pabrai"),
        Quote("Podemos encontrar muchas derrotas pero no debemos ser derrotados.", "Maya Angelou"),
        Quote("Saber no es suficiente; debemos aplicar. Desear no es suficiente; debemos hacer.", "Johann Wolfgang von Goethe"),
        Quote("Imagina que tu vida es perfecta en todos los aspectos; ¿cómo sería?", "Brian Tracy"),
        Quote("Generamos miedos mientras nos sentamos. Los superamos con la acción.", "Dr. Henry Link"),
        Quote("Si crees que puedes o crees que no puedes, tienes razón.", "Henry Ford"),
        Quote("La seguridad es principalmente una superstición. La vida es una aventura atrevida o nada.", "Helen Keller"),
        Quote("El que tiene confianza en sí mismo gana la confianza de los demás.", "Proverbio Hasídico"),
        Quote("El único límite a nuestra realización de mañana serán nuestras dudas de hoy.", "Franklin D. Roosevelt"),
        Quote("La creatividad es la inteligencia divirtiéndose.", "Albert Einstein"),
        Quote("Lo que te falta en talento lo puedes compensar con ganas, gestión y dando el 110% todo el tiempo.", "Don Zimmer"),
        Quote("Haz lo que puedes con lo que tienes, estés donde estés.", "Theodore Roosevelt"),
        Quote("Desarrolla el éxito a partir de los fracasos. El desaliento y el fracaso son dos de los peldaños más seguros hacia el éxito.", "Dale Carnegie"),
        Quote("La acción es la clave fundamental de todo éxito.", "Pablo Picasso"),
        Quote("El éxito es la suma de pequeños esfuerzos repetidos día tras día.", "Robert Collier"),
        Quote("Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de alguien más.", "Steve Jobs"),
        Quote("La motivación es lo que te pone en marcha. El hábito es lo que te mantiene.", "Jim Ryun"),
        Quote("No cuentes los días, haz que los días cuenten.", "Muhammad Ali"),
        Quote("La mejor forma de predecir el futuro es creándolo.", "Peter Drucker"),
        Quote("El éxito no es el final, el fracaso no es fatal: es el coraje para continuar lo que cuenta.", "Winston Churchill"),
        Quote("No busques los errores, busca un remedio.", "Henry Ford"),
        Quote("Tanto si piensas que puedes, como si piensas que no puedes, estás en lo cierto.", "Henry Ford"),
        Quote("Los obstáculos son esas cosas espantosas que ves cuando apartas los ojos de tu meta.", "Henry Ford"),
        Quote("La disciplina es el puente entre las metas y los logros.", "Jim Rohn"),
        Quote("El éxito llega para todos aquellos que están ocupados buscándolo.", "Henry David Thoreau"),
        Quote("La productividad nunca es un accidente. Siempre es el resultado de un compromiso con la excelencia, la planificación inteligente y el esfuerzo enfocado.", "Paul J. Meyer"),
        Quote("Si quieres ser feliz, establece una meta que guíe tus pensamientos, libere tu energía e inspire tus esperanzas.", "Andrew Carnegie"),
        Quote("El trabajo duro supera al talento cuando el talento no trabaja duro.", "Tim Notke"),
        Quote("No tienes que ser grande para empezar, pero tienes que empezar para ser grande.", "Zig Ziglar"),
        Quote("La única forma de hacer un gran trabajo es amar lo que haces.", "Steve Jobs"),
        Quote("La tragedia de la vida no reside en no alcanzar tu meta. La tragedia consiste en no tener ninguna meta que alcanzar.", "Benjamin Mays"),
        Quote("El éxito es caminar de fracaso en fracaso sin perder el entusiasmo.", "Winston Churchill"),
        Quote("Todo lo que siempre has querido está al otro lado del miedo.", "George Addair"),
        Quote("La excelencia no es un acto, sino un hábito.", "Aristóteles"),
        Quote("Para lograr grandes cosas, no solo debemos actuar, sino también soñar; no solo planificar, sino también creer.", "Anatole France"),
        Quote("Cree que puedes y ya habrás recorrido la mitad del camino.", "Theodore Roosevelt"),
        Quote("La vida es 10% lo que me pasa y 90% cómo reacciono ante ello.", "Charles Swindoll"),
        Quote("El momento en que te rindes es el momento en que dejas que alguien más gane.", "Kobe Bryant"),
        Quote("Un sueño no se hace realidad a través de la magia; requiere sudor, determinación y trabajo duro.", "Colin Powell"),
        Quote("Tu actitud, no tu aptitud, determinará tu altitud.", "Zig Ziglar"),
        Quote("Haz de cada día tu obra maestra.", "John Wooden"),
        Quote("Donde hay una voluntad, hay un camino.", "Proverbio"),
        Quote("Si no estás dispuesto a arriesgar lo inusual, tendrás que conformarte con lo ordinario.", "Jim Rohn"),
        Quote("El éxito suele llegar a quienes están demasiado ocupados para buscarlo.", "Henry David Thoreau"),
        Quote("Lo que haces hoy puede mejorar todos tus mañanas.", "Ralph Marston"),
        Quote("No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.", "John Wooden"),
        Quote("Empieza donde estás. Usa lo que tienes. Haz lo que puedes.", "Arthur Ashe"),
        Quote("Tus metas son las hojas de ruta que te guían y te muestran lo que es posible para tu vida.", "Les Brown"),
        Quote("El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", "Albert Schweitzer"),
        Quote("Nunca eres demasiado viejo para establecer otra meta o para soñar un nuevo sueño.", "C.S. Lewis"),
        Quote("La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", "Séneca"),
        Quote("No tienes que ver toda la escalera, solo da el primer paso.", "Martin Luther King Jr."),
        Quote("La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste.", "Newt Gingrich"),
        Quote("No esperes. El tiempo nunca será el adecuado.", "Napoleon Hill"),
        Quote("Todo lo que puedes imaginar es real.", "Pablo Picasso"),
        Quote("Hazlo o no lo hagas, pero no lo intentes.", "Yoda"),
        Quote("Céntrate en ser productivo en lugar de estar ocupado.", "Tim Ferriss"),
        Quote("La mejor salida es siempre a través.", "Robert Frost"),
        Quote("Para ganar a lo grande, a veces hay que correr grandes riesgos.", "Bill Gates"),
        Quote("Los desafíos hacen que la vida sea interesante y superarlos hace que la vida tenga sentido.", "Joshua J. Marine"),
        Quote("La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.", "Jimmy Johnson"),
        Quote("El éxito consiste en obtener lo que se desea. La felicidad en disfrutar de lo que se obtiene.", "Ralph Waldo Emerson"),
        Quote("Tu vida cambia el momento en que tomas una decisión nueva, congruente y comprometida.", "Tony Robbins"),
        Quote("Las oportunidades no ocurren, las creas tú.", "Chris Grosser"),
        Quote("El único lugar donde el éxito viene antes que el trabajo es en el diccionario.", "Vidal Sassoon"),
        Quote("El secreto para salir adelante es empezar.", "Mark Twain"),
        Quote("Lo que la mente puede concebir y creer, puede lograr.", "Napoleon Hill"),
        Quote("No se trata de las ideas. Se trata de hacer que las ideas se hagan realidad.", "Scott Belsky"),
        Quote("Siempre parece imposible hasta que se hace.", "Nelson Mandela"),
        Quote("He fallado más de 9000 tiros en mi carrera. He perdido casi 300 juegos. 26 veces se me confió el tiro ganador y fallé. He fallado una y otra vez en mi vida. Y es por eso que tengo éxito.", "Michael Jordan"),
        Quote("Si puedes soñarlo, puedes hacerlo.", "Walt Disney"),
        Quote("No te detengas cuando estés cansado. Detente cuando hayas terminado.", "Anónimo"),
        Quote("El éxito es para aquellos que tienen el coraje de soñar y correr el riesgo de vivir sus sueños.", "Anónimo"),
        Quote("No importa lo lento que vayas, siempre y cuando no te detengas.", "Confucio"),
        Quote("El poder de la imaginación nos hace infinitos.", "John Muir"),
        Quote("La única persona en la que estás destinado a convertirte es la persona que decidas ser.", "Ralph Waldo Emerson"),
        Quote("Ve con confianza en la dirección de tus sueños. Vive la vida que has imaginado.", "Henry David Thoreau"),
        Quote("Un viaje de mil millas comienza con un solo paso.", "Lao Tzu"),
        Quote("Lo que midas es lo que mejorarás.", "Peter Drucker"),
        Quote("Prefiero morir de pasión que de aburrimiento.", "Vincent van Gogh"),
        Quote("La simplicidad es la máxima sofisticación.", "Leonardo da Vinci"),
        Quote("El conocimiento es poder.", "Francis Bacon"),
        Quote("Lo que no nos mata nos hace más fuertes.", "Friedrich Nietzsche"),
        Quote("Sé el cambio que quieres ver en el mundo.", "Mahatma Gandhi"),
        Quote("Pienso, luego existo.", "René Descartes"),
        Quote("La vida es lo que pasa mientras estás ocupado haciendo otros planes.", "John Lennon"),
        Quote("Solo sé que no sé nada.", "Sócrates"),
        Quote("El genio es un uno por ciento de inspiración y un noventa y nueve por ciento de transpiración.", "Thomas Edison"),
        Quote("El que busca la verdad corre el riesgo de encontrarla.", "Isabel Allende"),
        Quote("Aquel que tiene un porqué para vivir se puede enfrentar a todos los cómos.", "Friedrich Nietzsche"),
        Quote("La verdadera sabiduría está en reconocer la propia ignorancia.", "Sócrates"),
        Quote("Aprender sin reflexionar es malgastar la energía.", "Confucio")
    )
}
