package com.syncro.domain.usecase

import com.syncro.domain.model.SyncroItem
import androidx.compose.ui.graphics.Color
import com.syncro.domain.repository.GoogleSyncRepository
import com.syncro.domain.repository.TaskRepository
import java.time.LocalDate
import javax.inject.Inject

class SaveTaskUseCase @Inject constructor(
    private val repository: TaskRepository,
    private val googleSyncRepository: GoogleSyncRepository
) {
    suspend operator fun invoke(
        title: String, 
        description: String, 
        date: LocalDate, 
        time: String,
        categoryText: String? = null,
        categoryColor: Color? = null
    ) {
        val task = SyncroItem.Task(
            id = "0", // Auto-generated by Room
            title = title,
            description = description,
            time = time,
            isCompleted = false,
            categoryText = categoryText,
            categoryColor = categoryColor
        )
        repository.insertTask(task, date)
        
        // Sincronizar con Google en segundo plano
        googleSyncRepository.uploadTaskToGoogle(title, description, date)
    }
}
